### ISSUE TITLE
Podman systemd unit type

### ISSUE THREAD

**Issue by vrothberg** [thkukuk/container-registry-systemd#2]
I've been browsing around what you folks in Kubic have been working on lately and found this repository. In case you run into issues running the systemd unit, I want to share two pointers:

* Consider changing to `type=Forking` and let conmon write the PIDFile (see https://www.redhat.com/sysadmin/podman-shareable-systemd-services).
* Running in cgroups v2, you may need to set `podman run **--cgroups=no-conmon**`.

I love the idea to pack the registry into an rpm :+1:

**Comment by thkukuk** [comment]
Thanks, I made some adjustments to our service files.
