### ISSUE TITLE
systemd service unit file is currently broken

### ISSUE THREAD

**Issue by IBue** [thkukuk/container-registry-systemd#3]
The service unit file does not set up the **sd_notify** mechanism between _systemd_ and _podman_ correctly.
In consequence of which the service does not get beyond its `activating` status; the container ends up being torn down and restarted continuously within the restart-limit.
The following modifications will fix this:
```systemd
c ExecStart=…/usr/bin/podman … --sdnotify=conmon …
+ NotifyAccess=all
```

Furthermore, the __shell wrapper can be omitted__. Though, extra attention has to be paid to the expansion of environment variables on the command line (here: `PODMAN_EXTRA_ARGS`).
Since _podman_ does not cope well with an explicit empty _positional_ argument in the middle, or one that contains spaces, brace expansion must be avoided for those:
```
ExecStart=/usr/bin/podman … $PODMAN_EXTRA_ARGS …
```
`${…}` expands to _one_ positional argument, even an empty one, while `$…` expands to zero or more positional arguments (cf. https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines)

_podman_ 4.0.3
_systemd_ 250

**Comment by thkukuk** [comment]
> Furthermore, the **shell wrapper can be omitted**. Though, extra attention has to be paid to the expansion of environment variables on the command line (here: `PODMAN_EXTRA_ARGS`). Since _podman_ does not cope well with an explicit empty _positional_ argument in the middle, or one that contains spaces, brace expansion must be avoided for those:

Funny that you describe why the shell wrapper is required by claiming at the same time it can be omitted.
Yes, it can be omitted if everybody is doing everything correct. But this never happens.

**Comment by thkukuk** [comment]
Works now
